services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"    # Expose Redis on port 6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"    # Expose RedisInsight on port 8001
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  redis_data:
